$(document).ready(function(){function d(a,b,c,l){c<=l?$(b).html(a):$(b).html(c)}function c(){var a=parseFloat($("#time_range").val()),b=parseFloat($("#mem_base_input").val()),c=parseFloat($("#mem_price_input").val()),l=parseFloat($("#card_prod_input").val()),g=parseFloat($("#card_ship_input").val()),h=parseFloat($("#labor_input").val()),d=parseFloat($("#mailing_input").val());parseFloat($("#churn_input").val());var r=parseFloat($("#rate_range").val())/100;h/=6;var u="$"+(a*b*(l+g+h+d)).toLocaleString(),
n=[.5,.65,.7],p=[.05,.12,.15],k=[.05,.15,.2],f=0,m;for(m=0;m<a;m+=.5){var e=Math.floor(m);e=n[e]*(l+g)+p[e]*h+k[e]*d;e/=2;f+=b*e}1E12<=f&&(f=f.toExponential());l="$"+Math.floor(f).toLocaleString();g=Math.floor(a*b*15/60)+" hours ";g=g.toLocaleString();h=Math.round(21*b/454*a).toLocaleString()+" lbs CO<sub>2</sub>";a="$"+(b*r*c*a).toLocaleString();b="<hr><h4>Total Saved Costs:</h4><p>"+l+"</p>";$("#cost_saved").html(l);$("#time_saved").html(g);$("#CO2_saved").html(h);$("#rev_lost").html(a);$("#cur_cost").html(u);
550>=$(window).width()?($(".mobile_foot").removeClass("hide"),$(".mobile_foot").addClass("show"),$("#mobile_results").html(b),$(".title").removeClass("head_reg"),$(".title").addClass("head_mob"),$(".logo").removeClass("logo_reg"),$(".logo").addClass("logo_mob")):($(".mobile_foot").removeClass("show"),$(".mobile_foot").addClass("hide"),$("#mobile_results").html(""),$(".title").removeClass("head_mob"),$(".title").addClass("head_reg"),$(".logo").removeClass("logo_mob"),$(".logo").addClass("logo_reg"))}
function v(a){return/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(String(a).toLowerCase())}function w(){var a=document.getElementById("toast");a.className="show_toast";setTimeout(function(){a.className=a.className.replace("show_toast","")},3E3)}function x(){var a=document.getElementById("toast_demo");a.className="show_toast_demo";setTimeout(function(){a.className=a.className.replace("show_toast_demo",
"")},3E3)}c();$(".mobile_foot").removeClass("fixed_pos");$(window).scroll(function(){400<=$(window).scrollTop()?$(".mobile_foot").addClass("fixed_pos"):$(".mobile_foot").removeClass("fixed_pos")});$(window).resize(function(){c()});document.getElementById("time_range").oninput=function(){var a=this.value,b="";b=1<a?b+("<h5>Over "+a+" Years</h5>"):b+("<h5>Over "+a+" Year</h5>");$("#timeline").html(b);c()};document.getElementById("rate_range").oninput=function(){var a="<p>With a <strong style = 'color: #4c944b;'>"+
this.value+"%</strong> increase due to our digital membership cards that's a <strong>revenue increase</strong> of</p>";$("#rev_text").html(a);c()};$("#mem_base_input").on("change keyup paste",function(){var a=$(this).val();d(1,"#mem_base_input",a,-1);c()});$("#mem_price_input").on("change keyup paste",function(){var a=$(this).val();d(1,"#mem_price_input",a,-1);c()});$("#card_prod_input").on("change keyup paste",function(){var a=$(this).val();d(1.25,"#card_prod_input",a,-1);c()});$("#card_ship_input").on("change keyup paste",
function(){var a=$(this).val();d(.5,"#card_ship_input",a,-1);c()});$("#labor_input").on("change keyup paste",function(){var a=$(this).val();d(1,"#labor_input",a,-1);c()});$("#mailing_input").on("change keyup paste",function(){var a=$(this).val();d(1,"#mailing_input",a,-1);c()});$("#churn_input").on("change keyup paste",function(){var a=$(this).val();d(1,"#churn_input",a,-1);c()});$("#submit_button").click(function(){var a=$("#email_input").val();if(valid=v(a)){setTimeout(function(){w()},650);email_internal=
"Digital Membership ROI Inquiry from: "+a;email_internal=1==$("#opt_in").is(":checked")?email_internal+"<p>Subscribed: Yes</p>":email_internal+"<p>Subscribed: No</p>";var b=parseFloat($("#time_range").val()),c=parseFloat($("#mem_base_input").val()),d=parseFloat($("#mem_price_input").val()),g=parseFloat($("#card_prod_input").val()),h=parseFloat($("#card_ship_input").val()),t=parseFloat($("#labor_input").val()),r=parseFloat($("#mailing_input").val()),u=parseFloat($("#churn_input").val())/100,n=parseFloat($("#rate_range").val())/
100;t/=6;var p=[.5,.65,.7],k=[.05,.12,.15],f=[.05,.15,.2],m=0,e;for(e=0;e<b;e+=.5){var q=Math.floor(e);q=p[q]*(g+h)+k[q]*t+f[q]*r;q/=2;m+=c*q}p="$"+Math.floor(m).toLocaleString();k=Math.floor(b*c*15/60)+" hours ";k=k.toLocaleString();f=Math.round(21*c/454*b).toLocaleString()+" lbs CO<sub>2</sub>";n="$"+(c*n*d*b).toLocaleString();email_internal+="<br><p><strong>Results:</strong><p><p>Member Base: "+c+"</p><p>Membership Price: "+d+"</p><p>Card Production Cost: "+g+"</p><p>Postage: "+h+"</p><p>Labor per hour: "+
t+"</p><p>Promotional Materials: "+r+"</p><p>Churn: "+u+"</p><br><br><p><strong>Reported Savings:</strong><p><h3>\ud83d\udcb0 Total Saved Costs: "+p+"</h3><h3>\u23f0 Total Saved Time: "+k+"</h3><h3>\ud83c\udf0e Total Carbon Footprint Reduced: "+f+"</h3><h3>\ud83d\udcb8 Total Revenue Inrease: "+n+"</h3><br><hr><br>";$.ajax({type:"POST",url:"https://mandrillapp.com/api/1.0/messages/send.json",data:{key:"QYjR7JYAhGtIfrvh7dni2g",message:{from_email:"hello@cuseum.com",to:[{email:a,name:a,type:"to"}],subject:"Results from Digital Membership ROI & Savings Calculator",
html:"<p>Hi there,</p><br><p>Running a membership program comes with a lot of responsibility and with traditional membership cards you may be spending more than you think. By offering your members digital membership cards you can create new <strong>outreach channels</strong>, offer <strong>greater convenience</strong>, <strong>reduce time and costs</strong>, <strong>increase renewals</strong>, and <strong>save the planet</strong>! Among the many advantages gained, here are a few you can expect to gain over just "+
(1<b?b+" years":b+" year")+".</p><p><strong>Here are your Digital Membership ROI Calculator Results<h4>\ud83d\udcb0 Total Saved Costs: "+p+"</h4><h4>\u23f0 Total Saved Time: "+k+"</h4><h4>\ud83c\udf0e Total Carbon Footprint Reduced: "+f+"</h4><h4>\ud83d\udcb8 Total Revenue Inrease: "+n+"</h4><br><hr><br><p>Want to learn more about our products? Schedule a free consultation with a Cuseum expert simply by replying to this email!</p><p>Best,</p><p>The Cuseum Team</p>"}}}).done(function(a){});$.ajax({type:"POST",
url:"https://mandrillapp.com/api/1.0/messages/send.json",data:{key:"QYjR7JYAhGtIfrvh7dni2g",message:{from_email:"hello@cuseum.com",to:[{email:"hello@cuseum.com",type:"to"},{email:"dan@cuseum.com",type:"to"}],subject:"Inquiry: Digital Membership ROI",html:email_internal}}}).done(function(a){})}else alert("Sorry, looks like that is an invalid email!")});$("#submit_button_demo").click(function(){var a=$("#email_input_demo").val();(valid=v(a))?(setTimeout(function(){x()},650),email_internal="Digital Membership ROI Inquiry from: "+
a,email_internal=1==$("#opt_in").is(":checked")?email_internal+"<p>Subscribed: Yes</p>":email_internal+"<p>Subscribed: No</p>",email_internal+="<br><p>"+a+" requested a digital membership demo</p><br><p>Lead Source: ROI calculator</p>",$.ajax({type:"POST",url:"https://mandrillapp.com/api/1.0/messages/send.json",data:{key:"QYjR7JYAhGtIfrvh7dni2g",message:{from_email:"hello@cuseum.com",to:[{email:"dan@cuseum.com",type:"to"}],subject:"Demo Request: Digital Membership ROI & Savings Calculator",html:email_internal}}}).done(function(a){})):
alert("Sorry, looks like that is an invalid email!")});$(".modal").on("hidden.bs.modal",function(){$("#email_input").val("");$("#email_input_demo").val("")})});